### ISSUE TITLE
[Feature] pre-commit-hook

### ISSUE THREAD

**Issue by romanagureev** [benber86/mamushi#54]
**Describe the feature you'd like**
Formatters are helpful when integrated into [`.pre-commit`](https://pre-commit.com/) and CI.

**Describe alternatives you've considered**
I did [local version](https://github.com/curvefi/storage-proofs/blob/520717cdec747f2abcfa7353d634bed83f580490/.pre-commit-config.yaml#L11-L20) that can be reduced to:
```yaml
repos:
  - repo: local
    hooks:
      - id: mamushi
        name: mamushi
        entry: mamushi --line-length 100
        files: "^contracts/.*\\.(vy|vyi)$"
        language: system
```

**Additional context**
Created [PR](https://github.com/pre-commit/identify/pull/508) with vyper extension. This will allow to use types explicitly:
```yaml
repos:
  - repo: local
    hooks:
      - id: mamushi
        name: mamushi
        entry: mamushi --line-length 100
        files: "^contracts/.*"
        types: [ vyper ]
        language: system
```
